eBoard: Servo Class Reference
Servo Class Reference
#include <eBoard.h>
Public Member Functions
Servo ()
uint8_t attach (int pin)
uint8_t attach (int pin, int min, int max)
void detach ()
void write (int value)
void writeMicroseconds (int value)
int read ()
int readMicroseconds ()
bool attached ()
Private Attributes
uint8_t servoIndex
int8_t min
int8_t max
Detailed Description
Definition at line 3580 of file eBoard.h.
Constructor & Destructor Documentation
Servo()
Servo::Servo ()
Definition at line 3685 of file eBoard.h.
References DEFAULT_PULSE_WIDTH, INVALID_SERVO, MAX_SERVOS, ServoCount, servoIndex, servos, servo_t::ticks, and usToTicks.
                {
     if( ServoCount < MAX_SERVOS) {
       this->servoIndex = ServoCount++;                    // assign a servo index to this instance
       servos[this->servoIndex].ticks = usToTicks(DEFAULT_PULSE_WIDTH);   // store default values  - 12 Aug 2009
     }
     else
       this->servoIndex = INVALID_SERVO ;  // too many servos
   }
Member Function Documentation
attach() [1/2]
uint8_t Servo::attach (int pin)
Definition at line 3693 of file eBoard.h.
References MAX_PULSE_WIDTH, and MIN_PULSE_WIDTH.
Referenced by setup().
{
     return this->attach(pin, MIN_PULSE_WIDTH, MAX_PULSE_WIDTH);
   }
attach() [2/2]
uint8_t Servo::attach (int pin, int min, int max)
Definition at line 3696 of file eBoard.h.
References initISR(), ServoPin_t::isActive, isTimerActive(), max, MAX_PULSE_WIDTH, MAX_SERVOS, min, MIN_PULSE_WIDTH, ServoPin_t::nbr, servo_t::Pin, SERVO_INDEX_TO_TIMER, servoIndex, and servos.
{
     if(this->servoIndex < MAX_SERVOS ) {
       pinMode( pin, OUTPUT) ;                                   // set servo pin to output
       servos[this->servoIndex].Pin.nbr = pin;
       // todo min/max check: abs(min - MIN_PULSE_WIDTH) /4 < 128
       this->min  = (MIN_PULSE_WIDTH - min)/4; //resolution of min/max is 4 uS
       this->max  = (MAX_PULSE_WIDTH - max)/4;
       // initialize the timer if it has not already been initialized
       timer16_Sequence_t timer = SERVO_INDEX_TO_TIMER(servoIndex);
       if(isTimerActive(timer) == false)
         initISR(timer);
       servos[this->servoIndex].Pin.isActive = true;  // this must be set after the check for isTimerActive
     }
     return this->servoIndex ;
   }
attached()
bool Servo::attached () inline
Definition at line 3756 of file eBoard.h.
References ServoPin_t::isActive, servo_t::Pin, servoIndex, and servos.
{
     return servos[this->servoIndex].Pin.isActive ;
   }
detach()
void Servo::detach ()
Definition at line 3711 of file eBoard.h.
References finISR(), ServoPin_t::isActive, isTimerActive(), servo_t::Pin, SERVO_INDEX_TO_TIMER, and servoIndex.
                      {
     servos[this->servoIndex].Pin.isActive = false;
     timer16_Sequence_t timer = SERVO_INDEX_TO_TIMER(servoIndex);
     if(isTimerActive(timer) == false) {
       finISR(timer);
     }
   }
read()
int Servo::read (void) inline
Definition at line 3744 of file eBoard.h.
References readMicroseconds(), SERVO_MAX, and SERVO_MIN.
   {
     return  map( this->readMicroseconds()+1, SERVO_MIN(), SERVO_MAX(), 0, 180);
   }
readMicroseconds()
int Servo::readMicroseconds ()
Definition at line 3748 of file eBoard.h.
References INVALID_SERVO, servoIndex, servos, ticksToUs, and TRIM_DURATION.
Referenced by read().
{
     unsigned int pulsewidth;
     if( this->servoIndex != INVALID_SERVO )
       pulsewidth = ticksToUs(servos[this->servoIndex].ticks)  + TRIM_DURATION ;   // 12 aug 2009
     else
       pulsewidth  = 0;
     return pulsewidth;
   }
write()
void Servo::write (int value)
Definition at line 3718 of file eBoard.h.
References MIN_PULSE_WIDTH, SERVO_MAX, SERVO_MIN, and writeMicroseconds().
Referenced by set_motor_speed(), set_steer_angle(), and setup().
{
     if(value < MIN_PULSE_WIDTH)
     {  // treat values less than 544 as angles in degrees (valid values in microseconds are handled as microseconds)
       if(value < 0) value = 0;
       if(value > 180) value = 180;
       value = map(value, 0, 180, SERVO_MIN(),  SERVO_MAX());
     }
     this->writeMicroseconds(value);
   }
writeMicroseconds()
void Servo::writeMicroseconds (int value)
Definition at line 3727 of file eBoard.h.
References MAX_SERVOS, SERVO_MAX, SERVO_MIN, servoIndex, servos, servo_t::ticks, TRIM_DURATION, and usToTicks.
Referenced by write().
{
     // calculate and store the values for the given channel
     byte channel = this->servoIndex;
     if( (channel < MAX_SERVOS) )   // ensure channel is valid
     {
       if( value < SERVO_MIN() )          // ensure pulse width is valid
         value = SERVO_MIN();
       else if( value > SERVO_MAX() )
         value = SERVO_MAX();
       value = value - TRIM_DURATION;
       value = usToTicks(value);  // convert to ticks after compensating for interrupt overhead - 12 Aug 2009
       uint8_t oldSREG = SREG;
       cli();
       servos[channel].ticks = value;
       SREG = oldSREG;
     }
   }
Member Data Documentation
max
int8_t Servo::max private
Definition at line 3594 of file eBoard.h.
Referenced by attach().
min
int8_t Servo::min private
Definition at line 3593 of file eBoard.h.
Referenced by attach().
servoIndex
uint8_t Servo::servoIndex private
Definition at line 3592 of file eBoard.h.
Referenced by attach(), attached(), detach(), readMicroseconds(), Servo(), and writeMicroseconds().
The documentation for this class was generated from the following file:
/eagleoutice/projects/github/eBoard/eBoard.h