eBoard: eBoard/examples/dancing_dragon/dancing_dragon.cpp File Reference
dancing_dragon.cpp File Reference
a dancing dragon :D
#include <eBoard.h>
Macros
#define EBOARD_I2C 0x1
we need the I2C functionality
#define EBOARD_LCD 0x1
we want to use the LCD
#define HIGHSPEED
for smooth animations (: It would be possible to disable so many things like EBOARD_DEBUG_MODE but this is an example!
Functions
int main (void)
Variables
PROGMEM const unsigned char bit_one []
first frame of the animation
PROGMEM const unsigned char bit_two []
second frame of the animation
PROGMEM const unsigned char bit_tre []
third frame of the animation
PROGMEM const unsigned char bit_for []
fourth frame of the animation
PROGMEM const unsigned char bit_fiv []
fifth frame of the animation
PROGMEM const unsigned char bit_six []
sixth frame of the animation
PROGMEM const unsigned char bit_sev []
seventh frame of the animation
PROGMEM const unsigned char bit_ait []
eigth frame of the animation
PROGMEM const unsigned char bit_nin []
ninth frame of the animation
PROGMEM const unsigned char bit_ten []
tenth frame of the animation
PROGMEM const unsigned char bit_elv []
eleventh frame of the animation
const unsigned char * buf [11]
to enable 'smooth' access (:
SoccerBoard board
the board object
LCD lcd (board)
the lcd object
Detailed Description
a dancing dragon :D
Definition in file dancing_dragon.cpp.
Macro Definition Documentation
EBOARD_I2C
#define EBOARD_I2C 0x1
we need the I2C functionality
Definition at line 6 of file dancing_dragon.cpp.
EBOARD_LCD
#define EBOARD_LCD 0x1
we want to use the LCD
Definition at line 8 of file dancing_dragon.cpp.
HIGHSPEED
#define HIGHSPEED
for smooth animations (: It would be possible to disable so many things like EBOARD_DEBUG_MODE but this is an example!
Definition at line 11 of file dancing_dragon.cpp.
Function Documentation
main()
int main (void)
Note
you can copy paste this code into your ARDUINO IDE - keep in mind to change the path!
Compiled Size for ARUDINO UNO: 17,664 bytes => 3.0: 15,468 bytes
Compiled Size for ARUDINO MEGA: 19,240 bytes => 3.0: 17,062 bytes
Definition at line 769 of file dancing_dragon.cpp.
References board, buf, LCD::changeBackground(), LCD::drawBitmap(), lcd, and SoccerBoard::msleep().
 {
   byte i;
   lcd.changeBackground(true);
   for(;;){
     for(i = 0; i < 11; i++){
       lcd.drawBitmap(buf[i], 3, 0, 16, 8);
       board.msleep(70);
     }
     for(i = 9; i > 0; i--) {
       lcd.drawBitmap(buf[i], 3, 0, 16, 8);
       board.msleep(70);
     }
   }
  return 0;
 }
Variable Documentation
bit_ait
PROGMEM const unsigned char bit_ait[]
eigth frame of the animation
Definition at line 484 of file dancing_dragon.cpp.
bit_elv
PROGMEM const unsigned char bit_elv[]
eleventh frame of the animation
Definition at line 685 of file dancing_dragon.cpp.
bit_fiv
PROGMEM const unsigned char bit_fiv[]
fifth frame of the animation
Definition at line 283 of file dancing_dragon.cpp.
bit_for
PROGMEM const unsigned char bit_for[]
fourth frame of the animation
Definition at line 216 of file dancing_dragon.cpp.
bit_nin
PROGMEM const unsigned char bit_nin[]
ninth frame of the animation
Definition at line 551 of file dancing_dragon.cpp.
bit_one
PROGMEM const unsigned char bit_one[]
first frame of the animation
Definition at line 15 of file dancing_dragon.cpp.
bit_sev
PROGMEM const unsigned char bit_sev[]
seventh frame of the animation
Definition at line 417 of file dancing_dragon.cpp.
bit_six
PROGMEM const unsigned char bit_six[]
sixth frame of the animation
Definition at line 350 of file dancing_dragon.cpp.
bit_ten
PROGMEM const unsigned char bit_ten[]
tenth frame of the animation
Definition at line 618 of file dancing_dragon.cpp.
bit_tre
PROGMEM const unsigned char bit_tre[]
third frame of the animation
Definition at line 149 of file dancing_dragon.cpp.
bit_two
PROGMEM const unsigned char bit_two[]
second frame of the animation
Definition at line 82 of file dancing_dragon.cpp.
board
SoccerBoard board
the board object
Definition at line 757 of file dancing_dragon.cpp.
Referenced by main().
buf
const unsigned char* buf[11]
Initial value:
= {bit_one,bit_two,bit_tre,bit_for,bit_fiv,bit_six,
                          bit_sev,bit_ait,bit_nin,bit_ten,bit_elv}
to enable 'smooth' access (:
Definition at line 753 of file dancing_dragon.cpp.
Referenced by main().
lcd
LCD lcd(board)
the lcd object
Referenced by main().