eBoard: /eagleoutice/projects/github/eBoard/examples/lcd_debug.cpp File Reference
lcd_debug.cpp File Reference
a lcd debug example
#include "/eagleoutice/projects/github/eBoard/eBoard.h"
Macros
#define EBOARD_I2C 0x1
we need the I2C functionality
#define EBOARD_LCD 0x1
we want to use the LCD
Functions
int eVirtual_main ()
[COPY&PASTE] Assures the existence of the "qfix-code-main-method"
Variables
SoccerBoard board
the board object
LCD lcd (board)
the lcd object
DynamixelBoard dBoard (board)
the dBoard object
AX12Servo links (dBoard, 1)
left servo
AX12Servo rechts (dBoard, 2)
right servo
Detailed Description
a lcd debug example
Definition in file lcd_debug.cpp.
Macro Definition Documentation
EBOARD_I2C
#define EBOARD_I2C 0x1
we need the I2C functionality
Definition at line 5 of file lcd_debug.cpp.
EBOARD_LCD
#define EBOARD_LCD 0x1
we want to use the LCD
Definition at line 7 of file lcd_debug.cpp.
Function Documentation
eVirtual_main()
int eVirtual_main ()
[COPY&PASTE] Assures the existence of the "qfix-code-main-method"
Note
you can copy paste this code into your ARDUINO IDE - keep in mind to change the path!
Compiled Size for ARUDINO UNO: 8,526 bytes => 3.0: 7,278 bytes Compiled Size for ARUDINO MEGA: 10,058 bytes => 3.0: 8,242 bytes
Definition at line 27 of file lcd_debug.cpp.
References DynamixelBoard::action(), board, LCD::changeBackground(), LCD::clear(), dBoard, AX12Servo::getPosition(), lcd, links, LCD::print(), rechts, SoccerBoard::sleep(), and AX12Servo::storePosition().
 {
     links.storePosition(40);
     rechts.storePosition(200);
     //lcd.changeID(0x3C);
     board.sleep(1);
     lcd.clear();
     lcd.print(links.getPosition());
     lcd.print(1,0,rechts.getPosition());
     dBoard.action();
     board.sleep(1);
     lcd.changeBackground(true);
     lcd.print(2,0,links.getPosition());
     lcd.print(3,0,rechts.getPosition());
     return 0;
   }
Variable Documentation
board
SoccerBoard board
the board object
Definition at line 10 of file lcd_debug.cpp.
Referenced by eVirtual_main().
dBoard
DynamixelBoard dBoard(board)
the dBoard object
Referenced by eVirtual_main().
lcd
LCD lcd(board)
the lcd object
Referenced by eVirtual_main().
links
AX12Servo links(dBoard, 1)
left servo
Note
untested!
Referenced by eVirtual_main().
rechts
AX12Servo rechts(dBoard, 2)
right servo
Note
untested
Referenced by eVirtual_main().