eBoard: ServoCds55 Struct Reference
ServoCds55 Struct Reference
#include <eBoard.h>
Public Member Functions
ServoCds55 (int CS=53)
void begin ()
void WritePos (int ID, int Pos)
void write (int ID, int Pos)
void setVelocity (int velocity)
void setPoslimit (int posLimit)
void rotate (int ID, int velocity)
void SetServoLimit (int ID, int upperLimit)
void SetMotormode (int ID, int velocity)
void SetID (int ID, int newID)
void Reset (int ID)
byte sendWait (const byte what)
Public Attributes
int velocity_temp
int upperLimit_temp
int cs
Detailed Description
Definition at line 1486 of file eBoard.h.
Constructor & Destructor Documentation
ServoCds55()
ServoCds55::ServoCds55 (int CS = 53)
Definition at line 1508 of file eBoard.h.
References upperLimit_temp, and velocity_temp.
                                          :cs(CS) {
               velocity_temp = 150;
               upperLimit_temp = 300;
             }
Member Function Documentation
begin()
void ServoCds55::begin (void)
Definition at line 1512 of file eBoard.h.
References eagle_impl::SPIClass::begin(), cs, eagle_impl::SPIClass::setClockDivider(), SPI, and SPI_CLOCK_DIV8.
Referenced by setup().
{
           pinMode(cs,OUTPUT);
           digitalWrite(cs,HIGH);
           SPI.begin ();
           SPI.setClockDivider(SPI_CLOCK_DIV8);
         }
Reset()
void ServoCds55::Reset (int ID)
Definition at line 1579 of file eBoard.h.
References cs, and sendWait().
{
           digitalWrite(cs, LOW);
           sendWait ('r'); sendWait (ID);
           sendWait ('\t'); sendWait ('\r'); sendWait ('\n');
           digitalWrite(cs, HIGH);
           delay(10);
         }
rotate()
void ServoCds55::rotate (int ID, int velocity)
Definition at line 1533 of file eBoard.h.
References SetMotormode(), and SetServoLimit().
                                                   { // Motor Mode
           SetServoLimit(ID,0);
           delay(100);
           SetMotormode(ID,velocity);
         }
sendWait()
byte ServoCds55::sendWait (const byte what)
Definition at line 1518 of file eBoard.h.
References SPI, and eagle_impl::SPIClass::transfer().
Referenced by Reset(), SetID(), SetMotormode(), SetServoLimit(), and WritePos().
{
           byte a = SPI.transfer (what);
           delayMicroseconds (20);
           return a;
         }
SetID()
void ServoCds55::SetID (int ID, int newID)
Definition at line 1571 of file eBoard.h.
References cs, and sendWait().
{
           digitalWrite(cs, LOW);
           sendWait ('i'); sendWait (ID);
           sendWait (newID);
           sendWait ('\t'); sendWait ('\r'); sendWait ('\n');
           digitalWrite(cs, HIGH);
           delay(10);
         }
SetMotormode()
void ServoCds55::SetMotormode (int ID, int velocity)
Definition at line 1561 of file eBoard.h.
References cs, and sendWait().
Referenced by rotate().
{
           int velocityB = (velocity>>8 & 0xff);
           int velocityS = (velocity & 0xff);
           digitalWrite(cs, LOW);
           sendWait ('m'); sendWait (ID);
           sendWait (velocityB); sendWait (velocityS);
           sendWait ('\t'); sendWait ('\r'); sendWait ('\n');
           digitalWrite(cs, HIGH);
           delay(10);
         }
setPoslimit()
void ServoCds55::setPoslimit (int posLimit) inline
Definition at line 1526 of file eBoard.h.
References upperLimit_temp.
                                                 {  // set servo pos limit
           upperLimit_temp =  posLimit;
         }
SetServoLimit()
void ServoCds55::SetServoLimit (int ID, int upperLimit)
Definition at line 1551 of file eBoard.h.
References cs, sendWait(), and upperLimit_temp.
Referenced by rotate(), AX12Servo::setID(), and write().
{
           int upperLimitB = (upperLimit_temp>>8 & 0xff);
           int upperLimitS =  (upperLimit_temp & 0xff);
           digitalWrite(cs, LOW);
           sendWait ('s'); sendWait (ID);
           sendWait (upperLimitB); sendWait (upperLimitS);
           sendWait ('\t'); sendWait ('\r'); sendWait ('\n');
           digitalWrite(cs, HIGH);
           delay(10);
         }
setVelocity()
void ServoCds55::setVelocity (int velocity) inline
Definition at line 1523 of file eBoard.h.
References velocity_temp.
Referenced by AX12Servo::setPosition().
                                                 {   //set servo velocity
           velocity_temp = velocity;
         }
write()
void ServoCds55::write (int ID, int Pos)
Definition at line 1529 of file eBoard.h.
References SetServoLimit(), upperLimit_temp, and WritePos().
Referenced by SoccerBoard::motor(), and AX12Servo::setPosition().
                                             {     //  Servo Mode
           SetServoLimit(ID,upperLimit_temp);
           WritePos(ID,Pos);// default velocity:150
         }
WritePos()
void ServoCds55::WritePos (int ID, int Pos)
Definition at line 1538 of file eBoard.h.
References cs, sendWait(), and velocity_temp.
Referenced by write().
{
           int PosB = (Pos>>8 & 0xff);//low
           int PosS = (Pos & 0xff);//high
           int velocityB = (velocity_temp>>8 & 0xff);
           int velocityS = (velocity_temp & 0xff);
           digitalWrite(cs, LOW);
           sendWait ('p'); sendWait (ID);
           sendWait (PosB); sendWait (PosS);
           sendWait (velocityB); sendWait (velocityS);
           sendWait ('\t'); sendWait ('\r'); sendWait ('\n');
           digitalWrite(cs, HIGH);
           delay(10);
         }
Member Data Documentation
cs
int ServoCds55::cs
Definition at line 1506 of file eBoard.h.
Referenced by begin(), Reset(), SetID(), SetMotormode(), SetServoLimit(), and WritePos().
upperLimit_temp
int ServoCds55::upperLimit_temp
Definition at line 1505 of file eBoard.h.
Referenced by ServoCds55(), AX12Servo::setID(), setPoslimit(), SetServoLimit(), and write().
velocity_temp
int ServoCds55::velocity_temp
Definition at line 1504 of file eBoard.h.
Referenced by ServoCds55(), setVelocity(), and WritePos().
The documentation for this struct was generated from the following file:
/eagleoutice/projects/github/eBoard/eBoard.h