eBoard: LCD Struct Reference
LCD Struct Reference
[I2C] [LCD] This is used to add support for OLED displays connected to the 'SoccerBoard'
#include <eBoard.h>
Public Member Functions
LCD (SoccerBoard &soccerBoard, optVAL_t id=0x3C)
The constructor.
bool changeID (optVAL_t newID=0x3C)
changes the address of the LCD display talked to
bool clear (void)
clears the LCD
void print (const char *data)
prints a string to the display
void print (int data)
prints an integer to the display
void print (optVAL_t line, optVAL_t col, const char *data)
prints a string to the display at a specific position
void print (optVAL_t line, optVAL_t col, int data)
prints an integer to the display at a specific position
void lightOn (void)
enable the backlight
void lightOff (void)
disable the backlight
bool reset (void)
clears the screen
bool init (void)
initializes the Display called by:
void drawBitmap (const unsigned char *bitmap, byte posX, byte posY, byte hiX, byte hiY)
draws a bitmap representet as an array of bytes
void changeMode (bool newMode=true)
enable or disable the display
bool setCursor (byte posX=0x0, byte posY=0x0)
set the position of the cursor
bool changeBrightness (byte val=0x64)
changes the brightness of the display
void changeBackground (bool newBackground=false)
changes the background of the display
Public Attributes
optVAL_t ID
ID of the Display.
Private Member Functions
void s2Cmd (optVAL_t o, optVAL_t t)
this function will execute two cmd sends without starting and without ending the transmission
void s1Cmd (optVAL_t o)
this function will execute one cmd send without starting and without ending the transmission
void s1Dat (optVAL_t o)
this function will execute one dat send without starting and without ending the transmission
Private Attributes
byte pX
the addressing mode (page/horizontal)
byte pY
posY
bool _cI
called_guard
Detailed Description
[I2C] [LCD] This is used to add support for OLED displays connected to the 'SoccerBoard'
Author
EagleoutIce
LCD refers to the connected OLED display
Copyright
This code is based on the offical library [https://github.com/deloarts/OLED_I2C_128x64_Monochrome_Library] if you wan't to use this library in any official purpose, send a message to deloarts. cheers!
Warning
the usage of the LCD will need many Space due to the fact that font is handled by arduino
Precondition
to use this class:
//#include <Wire.h> //With EBOARD_GUESSPATH this is NOT needed anymore :D
#define EBOARD_I2C 0x1 //do you think this is obsolete ? tell me :D
#define EBOARD_LCD 0x1
[I2C] [LCD] You can use this class like this:
//#include <Wire.h> //With EBOARD_GUESSPATH this is NOT needed anymore :D
#define EBOARD_I2C 0x1
#define EBOARD_LCD 0x1
//#include <SPI.h> //With EBOARD_GUESSPATH this is NOT needed anymore :D
#include "/home/eagleoutice/Dokumente/proj/_sia/src/eBoard.h"
SoccerBoard board;
LCD lcd(board);
int main() {
    board.sleep(2); // not needed (it's just funny :P)
    lcd.clear();
    lcd.print("Hallo Mama,\n Wie gehts'?");
    lcd.print(2,2,"-- Gut");
    lcd.print(3,0,42);
}
Note
positions will only apply if both of them are smaller as the maximum declared with LCD_HEIGHT and LCD_WIDTH
init() will be called on the first display access! [Version 2.2b 🐏 - Optimize it [52m]]
Definition at line 3876 of file eBoard.h.
Constructor & Destructor Documentation
LCD()
LCD::LCD (SoccerBoard & soccerBoard, optVAL_t id = 0x3C)
The constructor.
Parameters
soccerBoard the connected SoccerBoard object
id the ID of the LCD display. Can be identified via pingI2C()
Note
if EBOARD_NANO is set to 0x1 this will only take one argument [the id]
Member Function Documentation
changeBackground()
void LCD::changeBackground (bool newBackground = false) inline
changes the background of the display
Parameters
newBackground the new background of display
true: white
false: black
Referenced by main().
changeBrightness()
bool LCD::changeBrightness (byte val = 0x64) inline
changes the brightness of the display
Parameters
val the new brightness of display
Returns
true if the transmission was successful
false if there was one of the following errors:
buffer overflow
NACK on address
NACK on data
unknown error
changeID()
bool LCD::changeID (optVAL_t newID = 0x3C) inline
changes the address of the LCD display talked to
Parameters
newID the target ID of the LCD
Note
this calls LCD::init() by default!
Returns
true if the transmission was successful
false if there was one of the following errors:
buffer overflow
NACK on address
NACK on data
unknown error
changeMode()
void LCD::changeMode (bool newMode = true) inline
enable or disable the display
Parameters
newMode the mode the Display should have now
true: enabled
false: disabled
clear()
bool LCD::clear (void) inline
clears the LCD
Returns
true if the transmission was successful
false if there was one of the following errors:
buffer overflow
NACK on address
NACK on data
unknown error
Referenced by main().
drawBitmap()
void LCD::drawBitmap (const unsigned char * bitmap, byte posX, byte posY, byte hiX, byte hiY) inline
draws a bitmap representet as an array of bytes
Parameters
bitmap the array of bytes representing the bitmap to draw
posX the startPos abscissa
posY the startPos ordinate
hiX the width of the bitmap
hiY the height of the bitmap
Referenced by main().
init()
bool LCD::init (void) inline
initializes the Display called by:
LCD::LCD()
LCD::changeID()
Returns
true if the transmission was successful
false if there was one of the following errors:
buffer overflow
NACK on address
NACK on data
unknown error
lightOff()
void LCD::lightOff (void) inline
disable the backlight
This is similar to:
[LCD::]brightness(0);
lightOn()
void LCD::lightOn (void) inline
enable the backlight
This is similar with:
[LCD::]brightness(255);
print() [1/4]
void LCD::print (const char * data) inline
prints a string to the display
Parameters
data the string to print
Referenced by main().
print() [2/4]
void LCD::print (int data) inline
prints an integer to the display
Parameters
data the integer to print
print() [3/4]
void LCD::print (optVAL_t line, optVAL_t col, const char * data) inline
prints a string to the display at a specific position
Parameters
line the line to start at
col the col to start at
data the string to print
print() [4/4]
void LCD::print (optVAL_t line, optVAL_t col, int data) inline
prints an integer to the display at a specific position
Parameters
data the integer to print [if you want to apply precision you'll have to do it manually there is no float write to save memory]
line the line to start at
col the col to start at
reset()
bool LCD::reset (void) inline
clears the screen
Returns
true if the transmission was successful
false if there was one of the following errors:
buffer overflow
NACK on address
NACK on data
unknown error
s1Cmd()
void LCD::s1Cmd (optVAL_t o) inline private
this function will execute one cmd send without starting and without ending the transmission
Parameters
o the param
s1Dat()
void LCD::s1Dat (optVAL_t o) inline private
this function will execute one dat send without starting and without ending the transmission
Parameters
o the param
s2Cmd()
void LCD::s2Cmd (optVAL_t o, optVAL_t t) inline private
this function will execute two cmd sends without starting and without ending the transmission
Parameters
o the first param
t the second param
setCursor()
bool LCD::setCursor (byte posX = 0x0, byte posY = 0x0) inline
set the position of the cursor
Parameters
posX the new position abscissa
posY the new position ordinate
Returns
true if the transmission was successful
false if there was one of the following errors:
buffer overflow
NACK on address
NACK on data
unknown error
Member Data Documentation
_cI
bool LCD::_cI private
called_guard
Definition at line 4056 of file eBoard.h.
ID
optVAL_t LCD::ID
ID of the Display.
Definition at line 4044 of file eBoard.h.
pX
byte LCD::pX private
the addressing mode (page/horizontal)
Todo:
possbile Ads: scrollMode?; font? [size]; invert?
posX
Definition at line 4052 of file eBoard.h.
pY
byte LCD::pY private
posY
Definition at line 4054 of file eBoard.h.
The documentation for this struct was generated from the following file:
/eagleoutice/projects/github/eBoard/eBoard.h