eBoard: SoccerBoard Struct Reference
SoccerBoard Struct Reference
This is the SoccerBoard ghost struct :D.
#include <eagle_SoccerBoard.h>
Public Member Functions
SoccerBoard (void)
The constructor.
void motor (uint8_t id, int16_t val)
As requested this is the ultimate shortcut ;)
void motorsOff (void)
As requested this is the shortcut to disable the main motor.
void power (optVAL_t id, bool state)
Set the state of a certain D-pin.
void powerOn (optVAL_t id)
Set the state of a certain D-pin to HIGH.
void powerOff (optVAL_t id)
Set the state of a certain D-pin to LOW.
void sleep (uint16_t t)
Say goodnight!
void msleep (uint16_t t)
Say goodnight!
bool digital (optVAL_t id)
Reads a digital value from a pin.
optVAL_t analog (optVAL_t id)
Reads an analog value from a pin.
void reset (void)
Resets the Soccerboard if EBOARD_USE_RESET is set to true.
Detailed Description
This is the SoccerBoard ghost struct :D.
Author
EagleoutIce
Note
Some calls like led-calls won't have any effect due to the hardware of the UNO
But they will work on the MEGA!
You can use this class like this:
#include <eBoard.h>
//manual: '#include "/path/to/eBoard.h"'
bool toggle = true;
SoccerBoard board;
int main() {
    for(;;){
        board.power(3,toggle);
        board.sleep(1);
        toggle = !toggle;
    }
}
Definition at line 45 of file eagle_SoccerBoard.h.
Constructor & Destructor Documentation
SoccerBoard()
SoccerBoard::SoccerBoard (void) inline
The constructor.
Note
Its important to mention the fact that there is nothing interesting about this ;D
Member Function Documentation
analog()
optVAL_t SoccerBoard::analog (optVAL_t id) inline
Reads an analog value from a pin.
Parameters
id The id of the pin
Returns
returns the value read
Definition at line 256 of file eagle_SoccerBoard.h.
References readPin().
 {return readPin(id,0);}
digital()
bool SoccerBoard::digital (optVAL_t id) inline
Reads a digital value from a pin.
Parameters
id The id of the pin
Returns
returns the value read
Definition at line 255 of file eagle_SoccerBoard.h.
References readPin().
 {return readPin(id);}
motor()
void SoccerBoard::motor (uint8_t id, int16_t val)
As requested this is the ultimate shortcut ;)
Parameters
id set to
[DEFAULT]
0 it will access the main Motor (accessed with I2CInOut otherwise)
1 it will try to access the Servo with the lower ID
2 it will try to access the Servo with the higher ID
[EBOARD_HELPCAR]
0 it will access the main Motor
1 it will acces the steering Motor
val the value you wan't to send
[DFAULT]
if id = 0 : val has to be from -255 to 255. Dir will be decided by >0|<0
if id = 1|2: val has to be from 0 to 300
[EBOARD_HELPCAR]
val has to be from 0 to 255 | with id = 0; 90 means stop
motorsOff()
void SoccerBoard::motorsOff (void)
As requested this is the shortcut to disable the main motor.
msleep()
void SoccerBoard::msleep (uint16_t t) inline
Say goodnight!
Parameters
t time in milliseconds the UNO gets to sleep ;)
Definition at line 254 of file eagle_SoccerBoard.h.
Referenced by main().
 {delay(t);}
power()
void SoccerBoard::power (optVAL_t id, bool state) inline
Set the state of a certain D-pin.
Note
unlike the soccerboard you can (if SHIFT_REGISTER enabled) use pinIDs from 100 to 131 (if provided by SN74HC595) directly to set shift-register Pins
if you want to have e.g. 64 bits you can hack the specific code (shiftAll()) to your needs;)
Parameters
id The id of the pin
state The state the pin should have
Definition at line 250 of file eagle_SoccerBoard.h.
References writePin().
Referenced by powerOff(), and powerOn().
 {writePin(id,state);}
powerOff()
void SoccerBoard::powerOff (optVAL_t id) inline
Set the state of a certain D-pin to LOW.
Note
unlike the soccerboard you can (if SHIFT_REGISTER enabled) use pinIDs from 100 to 131 (if provided by SN74HC595) directly to set shift-register Pins
if you want to have e.g. 64 bits you can hack the specific code (shiftAll()) to your needs;)
shortcut for power(id, LOW)
Parameters
id The id of the pin
Definition at line 252 of file eagle_SoccerBoard.h.
References power().
 {this->power(id,0);}
powerOn()
void SoccerBoard::powerOn (optVAL_t id) inline
Set the state of a certain D-pin to HIGH.
Note
unlike the soccerboard you can (if SHIFT_REGISTER enabled) use pinIDs from 100 to 131 (if provided by SN74HC595) directly to set shift-register Pins
if you want to have e.g. 64 bits you can hack the specific code (shiftAll()) to your needs;)
shortcut for power(id, HIGH)
Parameters
id The id of the pin
Definition at line 251 of file eagle_SoccerBoard.h.
References power().
 {this->power(id,1);}
reset()
void SoccerBoard::reset (void) inline
Resets the Soccerboard if EBOARD_USE_RESET is set to true.
sleep()
void SoccerBoard::sleep (uint16_t t) inline
Say goodnight!
Parameters
t time in seconds the UNO gets to sleep ;)
Definition at line 253 of file eagle_SoccerBoard.h.
Referenced by main().
 {delay(1000*t);}
The documentation for this struct was generated from the following file:
eBoard/source/eagle_SoccerBoard.h