eBoard: NeoPixel Struct Reference
NeoPixel Struct Reference
[NEO] this allows you to access Adafruit LED-stripes
#include <eagle_NeoPixel.h>
Public Member Functions
NeoPixel (uint16_t n, uint8_t p=6, uint16_t t=((1<< 6)|(1<< 4)|(0<< 2)|(2))+0x0000)
this is the default constructor that should be used whenever the amount of leds etc... connected is known at compile time (most cases)
NeoPixel (void)
the empty constructor
~NeoPixel (void)
the destructor [calling free on pixel and freeing input pin]
void begin (void)
this has to be called to start the communcation (you should call NeoPixel::setPin() before)
void show (void)
this will reveal the setPixels [via NeoPixel::setPixelColor() etc...]
void setPin (uint8_t p)
sets pin for communication
void setPixelColor (uint16_t n, uint8_t r, uint8_t g, uint8_t b)
sets the rgb color of a specific pixel
void setPixelColor (uint16_t n, uint8_t r, uint8_t g, uint8_t b, uint8_t w)
sets the rgbw color of a specific pixel
void setPixelColor (uint16_t n, uint32_t c)
sets the rgbw color of a specific pixel
void setBrightness (uint8_t val)
changes the brightness for all further acceses via NeoPixel::setPixelColor()
void clear (void)
this will reset all set pixels [won't call NeoPixel::show()]
void updateLength (uint16_t n)
this changes the length of the connected LED stripe
void updateType (uint16_t t)
this changes the type of communication between arduino and LED stripe
uint8_t * getPixels (void) const
this will give you access to the pixels
uint8_t getBrightness (void) const
returns the current set brightness
int8_t getPin (void)
this will return the set data pin
uint16_t numPixels (void) const
returns the size of the LED stripe
uint32_t getPixelColor (uint16_t n) const
returns the color of a specific pixel
bool canShow (void)
this will determine if the next show is available [last show finished]
Static Public Member Functions
static uint32_t Color (uint8_t r, uint8_t g, uint8_t b)
returns a color value that can be used with NeoPixel::setPixelColor()
static uint32_t Color (uint8_t r, uint8_t g, uint8_t b, uint8_t w)
returns a color value that can be used with NeoPixel::setPixelColor()
Protected Attributes
bool is800KHz
determines the speed the communcation is working on
bool begun
true if NeoPixel::begin has been called
uint16_t numLEDs
stores the amount of LEDs
uint16_t numBytes
stores the byte size [pixels] used internally
int8_t pin
stores the pin -1 if the pin wasn't set
uint8_t brightness
stores the brightness
uint8_t * pixels
stores the pixels
uint8_t aOffset [4]
stores the offsets in rgbw format
uint32_t endTime
stores the last call time of show for NeoPixel::canShow()
Detailed Description
[NEO] this allows you to access Adafruit LED-stripes
Author
Adafruit
Note
this code was documented and modified by EagleoutIce in 2018 for custom use!
Precondition
to use this class:
#define EBOARD_NEO 0x1
[NEO] You can use this class like this:
#define EBOARD_NEO 0x1
#include <eBoard.h>
//manual: '#include "/path/to/eBoard.h"'
NeoPixel nPixel = NeoPixel(5);
int main() {
    nPixel.begin();
    nPixel.setPixelColor(3,NeoPixel::Color(0,255,0)); //the order is based on your configuration
    nPixel.show();
}
There is also an example code provided with this library, called neo_animation
If you've included eBoard as an Arduino Library it is available via the examples tab [as the corresponding .ino file]
Keep in mind:
The NeoPixel uses a one-wire interface and is therefore very timing sensitive!
You can't expect any interrupt or buffer working properly!
So you should always have a listening line that will be disabled whenever NeoPixel::show() is called
Definition at line 116 of file eagle_NeoPixel.h.
Constructor & Destructor Documentation
NeoPixel() [1/2]
NeoPixel::NeoPixel (uint16_t n, uint8_t p = 6, uint16_t t = ((1<< 6)|(1<< 4)|(0<< 2)|(2))+0x0000)
this is the default constructor that should be used whenever the amount of leds etc... connected is known at compile time (most cases)
Parameters
n the amount of LEDs connected to the pin
p the (data) pin connected to the arduino
t the type of com the NeoPixel should be talked to
NeoPixel() [2/2]
NeoPixel::NeoPixel (void)
the empty constructor
Note
this has to be called manually then:
NeoPixel::updateType()
NeoPixel::updateLength()
NeoPixel::setPin()
~NeoPixel()
NeoPixel::~NeoPixel (void)
the destructor [calling free on pixel and freeing input pin]
Member Function Documentation
begin()
void NeoPixel::begin (void)
this has to be called to start the communcation (you should call NeoPixel::setPin() before)
Referenced by main().
canShow()
bool NeoPixel::canShow (void) inline
this will determine if the next show is available [last show finished]
Returns
true if it is possible
clear()
void NeoPixel::clear (void)
this will reset all set pixels [won't call NeoPixel::show()]
Color() [1/2]
static uint32_t NeoPixel::Color (uint8_t r, uint8_t g, uint8_t b) inline static
returns a color value that can be used with NeoPixel::setPixelColor()
Parameters
r the red color [can be different dependent on NeoPixel::updateType()]
g the green color [can be different dependent on NeoPixel::updateType()]
b the blue color [can be different dependent on NeoPixel::updateType()]
Referenced by shiftPx().
Color() [2/2]
static uint32_t NeoPixel::Color (uint8_t r, uint8_t g, uint8_t b, uint8_t w) inline static
returns a color value that can be used with NeoPixel::setPixelColor()
Parameters
r the red color [can be different dependent on NeoPixel::updateType()]
g the green color [can be different dependent on NeoPixel::updateType()]
b the blue color [can be different dependent on NeoPixel::updateType()]
w the 'white' color [can be different dependent on NeoPixel::updateType()]
getBrightness()
uint8_t NeoPixel::getBrightness (void) const inline
returns the current set brightness
Returns
the brightness set via NeoPixel::setBrightness()
getPin()
int8_t NeoPixel::getPin (void) inline
this will return the set data pin
Returns
the dataPin set via NeoPixel::setPin()
getPixelColor()
uint32_t NeoPixel::getPixelColor (uint16_t n) const
returns the color of a specific pixel
Returns
the color value
getPixels()
uint8_t* NeoPixel::getPixels (void) const inline
this will give you access to the pixels
Returns
the pixels 'set'
numPixels()
uint16_t NeoPixel::numPixels (void) const inline
returns the size of the LED stripe
Returns
the size set via NeoPixel::updateLength()
setBrightness()
void NeoPixel::setBrightness (uint8_t val)
changes the brightness for all further acceses via NeoPixel::setPixelColor()
Parameters
val the brightness-value
Note
call this only once xD as this will affect timing
Referenced by main().
setPin()
void NeoPixel::setPin (uint8_t p)
sets pin for communication
Parameters
p the (data) pin connected to the arduino
setPixelColor() [1/3]
void NeoPixel::setPixelColor (uint16_t n, uint8_t r, uint8_t g, uint8_t b)
sets the rgb color of a specific pixel
Parameters
n the index of the pixel (starting at 0)
r the red color [can be different dependent on NeoPixel::updateType()]
g the green color [can be different dependent on NeoPixel::updateType()]
b the blue color [can be different dependent on NeoPixel::updateType()]
Referenced by shiftPx().
setPixelColor() [2/3]
void NeoPixel::setPixelColor (uint16_t n, uint8_t r, uint8_t g, uint8_t b, uint8_t w)
sets the rgbw color of a specific pixel
Parameters
n the index of the pixel (starting at 0)
r the red color [can be different dependent on NeoPixel::updateType()]
g the green color [can be different dependent on NeoPixel::updateType()]
b the blue color [can be different dependent on NeoPixel::updateType()]
w the 'white' color [can be different dependent on NeoPixel::updateType()]
setPixelColor() [3/3]
void NeoPixel::setPixelColor (uint16_t n, uint32_t c)
sets the rgbw color of a specific pixel
Parameters
n the index of the pixel (starting at 0)
c the NeoPixel::Color() you want
show()
void NeoPixel::show (void)
this will reveal the setPixels [via NeoPixel::setPixelColor() etc...]
Referenced by shiftPx().
updateLength()
void NeoPixel::updateLength (uint16_t n)
this changes the length of the connected LED stripe
Parameters
n the new length
updateType()
void NeoPixel::updateType (uint16_t t)
this changes the type of communication between arduino and LED stripe
Parameters
t the new type [constant starting with EBOARD_NEO]
Member Data Documentation
aOffset
uint8_t NeoPixel::aOffset[4] protected
stores the offsets in rgbw format
Definition at line 257 of file eagle_NeoPixel.h.
begun
bool NeoPixel::begun protected
true if NeoPixel::begin has been called
Definition at line 242 of file eagle_NeoPixel.h.
brightness
uint8_t NeoPixel::brightness protected
stores the brightness
Definition at line 253 of file eagle_NeoPixel.h.
endTime
uint32_t NeoPixel::endTime protected
stores the last call time of show for NeoPixel::canShow()
Definition at line 259 of file eagle_NeoPixel.h.
is800KHz
bool NeoPixel::is800KHz protected
determines the speed the communcation is working on
Definition at line 240 of file eagle_NeoPixel.h.
numBytes
uint16_t NeoPixel::numBytes protected
stores the byte size [pixels] used internally
Definition at line 246 of file eagle_NeoPixel.h.
numLEDs
uint16_t NeoPixel::numLEDs protected
stores the amount of LEDs
Definition at line 244 of file eagle_NeoPixel.h.
pin
int8_t NeoPixel::pin protected
stores the pin -1 if the pin wasn't set
Definition at line 251 of file eagle_NeoPixel.h.
pixels
uint8_t* NeoPixel::pixels protected
stores the pixels
Definition at line 255 of file eagle_NeoPixel.h.
The documentation for this struct was generated from the following file:
eBoard/source/eagle_NeoPixel.h